# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

jobs:
  # First job exists to setup variables/declare dependencies for the docker
  # build
  - job: setup
    steps:
      - bash: ./set-build-variables.sh
        name: set_vars
        displayName: "Set build variables from repo"

  # Second job logs into docker registry and simply runs docker build/push with
  # tag information from the first job
  - job: build
    dependsOn: setup

    variables:
      image_version: $[ dependencies.A.outputs['set_vars.image_version'] ]

    steps:
      - task: Docker@2
        inputs:
          command: login
          containerRegistry: emarcotte-registry

      - task: Docker@2
        displayName: "Build and push"
        inputs:
          command: buildAndPush
          repository: sandbox-20200610-98rxvk/deployment_app_1
          tags: |
            $(image_version)

