apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-app-1
  name: deployment-app-1
  namespace: {{ required ".Values.namespace is required" .Values.namespace | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: deployment-app-1

  template:
    metadata:
      labels:
        app: deployment-app-1

    spec:
      containers:
      - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: deployment-app-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
